name: backstreets_widgets
version: 0.26.1
description: A package of useful widgets which reduce code, and guarantee an accessible experience on multiple platforms.
repository: https://github.com/chrisnorman7/backstreets_widgets

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.1.0-0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dio: ^5.4.3+1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
